#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MEMORY_LIMIT=$(((BENCHTOOLS_RSSMEM_LIMIT / 1024) - 1024))
TIME_LIMIT=$((BENCHTOOLS_WCTIME_LIMIT - 60))

runlim -s $MEMORY_LIMIT -r $TIME_LIMIT python3 $SCRIPT_DIR/runner.py $BENCHTOOLS_PARAMS --target $BENCHTOOLS_INSTANCE
